(define <= (lambda (a b) (or (= a b) (< a b))))
(define (sum-of-squares a b)
  (+ (* a a) (* b b)))
(define (f a b c)
    (cond ((and (<= a b) (<= a c)) (sum-of-squares b c))
          ((and (<= b a) (<= b c)) (sum-of-squares a c))
          ((and (<= c a) (<= c b)) (sum-of-squares a b))))